### ISSUE TITLE
INFOGRAFIA

### ISSUE THREAD

**Issue by Kim-Mendoza3** [SistemasTecTlaxiaco/actividad-4-infografia-de-libreria-Kim-Mendoza3#1]
https://drive.google.com/file/d/1cOsGXSNN3HIOlUZz1j5alw6sAqOHHFFE/view?usp=sharing

**Comment by KevCH24** [comment]
Calificación: 20 
Muy bien

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
